// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM4EkvG2IZs9r1Azs8T8znNi6A_HMAAvA',
    appId: '1:996801757115:android:8f9f61b27f91fc324f8e9e',
    messagingSenderId: '996801757115',
    projectId: 'gs-expansion-test2-fb0a6',
    storageBucket: 'gs-expansion-test2-fb0a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC43c6-EeUYw4lBJWDIWHstJQRtr8j1XfE',
    appId: '1:996801757115:ios:9831a9a3ddc367ae4f8e9e',
    messagingSenderId: '996801757115',
    projectId: 'gs-expansion-test2-fb0a6',
    storageBucket: 'gs-expansion-test2-fb0a6.appspot.com',
    iosClientId: '996801757115-9o7vusf9nn1nkfiesdm0s7rl67cnpo50.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenlyLike',
  );
}
